### ISSUE TITLE
HDR file is created emty using `scylladb/cassandra-stress:3.13.0` docker

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/cassandra-stress#23] opened 2024-09-11 10:00 UTC
When I ran performance test using `scylladb/cassandra-stress:3.13.0` and `scylladb/cassandra-stress:3.14.0` docker, HDR files were created empty. (https://argus.scylladb.com/test/87b0dae5-bcdf-426b-a8fe-30cb11c8cee1/runs?additionalRuns[]=f6401e60-3cdb-48b8-956f-24abe6b74d7d)

Using `docker.io/scylladb/hydra-loaders:cassandra-stress-6.0-20240701` it was worked ok (https://argus.scylladb.com/test/87b0dae5-bcdf-426b-a8fe-30cb11c8cee1/runs?additionalRuns[]=b92d02dd-5d50-47e6-8011-b89ede3ba895)

**Comment by CodeLieutenant** [comment] 2024-09-11 11:59
I'm not able to reproduce the issue on my machine, when I run it locally

```
docker run --network host -v ./logs:/var/log/cassandra-stress -it scylladb/cassandra-stress 'mkdir -p /var/log/cassandra-stress/ && cassandra-stress write n=10000 cl=ONE -rate threads=5 -log hdrfile=/var/log/cassandra-stress/output.hdr'
```
And the `output.hdr` is not empty  

[output.txt](https://github.com/user-attachments/files/16963228/output.txt)

This is how it looks like

**Comment by fruch** [comment] 2024-09-11 12:01
> I'm not able to reproduce the issue on my machine, when I run it locally
> 
> ```
> docker run --network host -v ./logs:/var/log/cassandra-stress -it scylladb/cassandra-stress 'mkdir -p /var/log/cassandra-stress/ && cassandra-stress write n=10000 cl=ONE -rate threads=5 -log hdrfile=/var/log/cassandra-stress/output.hdr'
> ```
> And the `output.hdr` is not empty  
> 
> [output.txt](https://github.com/user-attachments/files/16963228/output.txt) *had to rename it, `.hdr` is not supported by GitHub 
> 
> This is how it looks like

I've seen that too

I suspect $HOME isn't defined in our docker for some reason, or we mount into a non-existent directory.

**Comment by CodeLieutenant** [comment] 2024-09-12 10:51
Issue fixed with https://github.com/scylladb/scylla-cluster-tests/pull/8646

**Closed by CodeLieutenant** 2024-09-12 10:51 UTC
